In [ ]:
#question 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
#            enhance Python's capabilities for numerical operations?
#answer      in python we have lists that serve the purpose of arrays but they are slow to process. numPy aims to provide an array object that is upto
#            50X faster than list. 
#             advantages:- 1. performance
#                          2. memory efficiency
#                          3.extensive mathematical functions
#                          4.interoperability
#            array creation,mathematical operations,array indexing and slicing,broadcasting are the features that enhance python capabilities for 
#            numerical operations.


In [7]:
#question 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
#            other?
#answer      np.mean() is used to calculate arithmatic mean whereas np.average is used to calculated mean as well as weighted average.
#            weight can not be passed through the parameter of given function, weight can  be passed through the parameter of given function
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.mean(arr)

5.5

In [11]:
weight=np.array([4,5,6,12,15,10,2,8,19,20])
weight

array([ 4,  5,  6, 12, 15, 10,  2,  8, 19, 20])

In [12]:
np.average(weight)

10.1

In [17]:
#question 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
#            arrays?
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [24]:
b=np.flip(a, axis=0)
b

array([5, 4, 3, 2, 1])

In [25]:
c=np.array([[1,2],[2,3],[4,5]])

In [26]:
c

array([[1, 2],
       [2, 3],
       [4, 5]])

In [28]:
d=np.flip(c,axis =0)
d

array([[4, 5],
       [2, 3],
       [1, 2]])

In [30]:
#question 4:-  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
#              in memory management and performance?
#answer        datatype in numPy is used to specify the type of data stored in variable.
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [31]:
type(arr1)

numpy.ndarray

In [33]:
arr1.ndim

1

In [ ]:
c=np.array([[1,2],[2,3],[4,5]])

In [34]:
type(c)

numpy.ndarray

In [ ]:
#datatype are crucial inprogramming because they help to enforce code reliabilityand efficiency.they allow the compiler 
#to allocate the right amount of memoryfor the data and perform the correct operation on it.

In [35]:
#question 5:- Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
#answer       An ndarray is a multi dimensional array of items of same type and size.an ndarray has an associated data type object which specifies
#             the dtype stored in the ndarray
#             list are heterogrneous in nateure but ndarrays are homogeneous in nature
lis=[1,2,3.5,"preeti",True]
lis

[1, 2, 3.5, 'preeti', True]

In [37]:
ar=np.array([1,2,3,4])
ar

array([1, 2, 3, 4])

In [ ]:
#question 6:- . Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations?
#answer         in data science ,efficency and speed are paramount. NumPy which stands for numerical python offers significant advantages over 
#               traditional lists for data manipulation and processing. it has a powerful library,that provides an array object much more suited
#               for numerical data. numpy arrays are designed to handle large data set efficiently and with a much lower memory footprint. when 
#               you are dealing with masive datasets  as is often the case in data science,this efficiency can make a world of difference in terms
#               of performance and scalability.

In [38]:
#question 7:-  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output?
#answer        numpy vstack and hstack are the tools for combining numpy array together.numpy hstack combines array horizontally and numpy vstack
#              combines array vertically
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,7,8,9])
arr1

array([1, 2, 3, 4, 5])

In [41]:
arr=np.hstack((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 4, 5, 7, 8, 9])

In [42]:
arr3=np.vstack((arr1,arr2))
arr3

array([[1, 2, 3, 4, 5],
       [4, 5, 7, 8, 9]])

In [43]:
#question 8:-  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
#              array dimensions?
#answer        numpy.fliplr(array) : Flip array(entries in each column) in left-right direction
arr1=np.array([[1,2],[2,3],[3,4],[5,6]])
arr1

array([[1, 2],
       [2, 3],
       [3, 4],
       [5, 6]])

In [44]:
np.fliplr(arr1)

array([[2, 1],
       [3, 2],
       [4, 3],
       [6, 5]])

In [46]:
# flipud:-  Reverse the order of elements along axis 0 (up/down).
arr2=np.array([[1,2,3],[2,3,4],[4,5,6]])
arr2

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [47]:
np.flipud(arr2)

array([[4, 5, 6],
       [2, 3, 4],
       [1, 2, 3]])

In [49]:
#question 9:-  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
#answer      
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [51]:
np.array_split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
#numpy.array_split() splitting into equal or nearly equal sub-arrays or is similar to numpy.split(), 
#but it allows for uneven splitting of arrays. This is useful when the array cannot be evenly divided by the specified number of splits.
#numpy.array_split(array, 4) splits the array into four parts, accommodating the uneven division.

In [52]:
#question 10:- Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
#              operations?
#answer        The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during arithmetic operations. 
#              This process involves certain rules that allow the smaller array to be ‘broadcast’ across the larger one,
#              ensuring that they have compatible shapes for these operations.
#              Broadcasting is not limited to two arrays; it can be applied over multiple arrays as well.
#              Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops. 
#              This is because NumPy is implemented in C Programming, which is a very efficient language.
a = np.array([5, 7, 3, 1]) 
b = np.array([90, 50, 0, 30]) 
c=a*b
c

array([450, 350,   0,  30])