In [7]:

import numpy as np
import random
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
a= np.random.randint(1,100,(3,3))
a

array([[31, 16, 38],
       [75, 43, 41],
       [93, 98, 31]], dtype=int32)

In [8]:
a.T

array([[31, 75, 93],
       [16, 43, 98],
       [38, 41, 31]], dtype=int32)

In [9]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
arr= np.random.randint(1,10,(2,5))
arr

array([[5, 8, 1, 9, 4],
       [3, 6, 5, 7, 2]], dtype=int32)

In [11]:
arr.reshape(5,2)

array([[5, 8],
       [1, 9],
       [4, 3],
       [6, 5],
       [7, 2]], dtype=int32)

In [13]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
arr2= np.random.uniform(1.0,10.0,(4,4))
arr2

array([[1.68609317, 8.36188641, 9.5516059 , 3.595767  ],
       [1.11247004, 6.05560317, 8.47402831, 9.72427978],
       [8.40140594, 9.69994876, 4.68896836, 7.14448067],
       [3.62132715, 5.78460289, 2.1592927 , 8.71518426]])

In [16]:
arr2=np.pad(arr2, pad_width=1,mode="constant",constant_values=0)
arr2

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 1.68609317, 8.36188641, 9.5516059 , 3.595767  ,
        0.        ],
       [0.        , 1.11247004, 6.05560317, 8.47402831, 9.72427978,
        0.        ],
       [0.        , 8.40140594, 9.69994876, 4.68896836, 7.14448067,
        0.        ],
       [0.        , 3.62132715, 5.78460289, 2.1592927 , 8.71518426,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [12]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5
import numpy as np
a=np.arange(10,60,5)
a


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [17]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
#(uppercase, lowercase, title case, etc.) to each element

list=["python","numpy","pandas"]
list
b=np.array(list)
np.char.upper(b)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [18]:
np.char.lower(b)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [24]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array
list=["python","numpy","pandas"]
list
d=np.array(list)
d
r=np.char.join(" ",d)
print(r)

['p y t h o n' 'n u m p y' 'p a n d a s']


In [29]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
arr1=np.array([[1,2,3],[4,5,6],[3,4,8]])
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 8]])

In [30]:
arr2=np.array([[3,5,7],[2,4,6],[1,3,6]])
arr2

array([[3, 5, 7],
       [2, 4, 6],
       [1, 3, 6]])

In [31]:
arr1+arr2

array([[ 4,  7, 10],
       [ 6,  9, 12],
       [ 4,  7, 14]])

In [32]:
arr1-arr2

array([[-2, -3, -4],
       [ 2,  1,  0],
       [ 2,  1,  2]])

In [33]:
arr1/arr2

array([[0.33333333, 0.4       , 0.42857143],
       [2.        , 1.25      , 1.        ],
       [3.        , 1.33333333, 1.33333333]])

In [34]:
arr1*arr2

array([[ 3, 10, 21],
       [ 8, 20, 36],
       [ 3, 12, 48]])

In [54]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
a=np.eye(5)
a
np.fromfunction(lambda i,j:i==j,(2,2))

array([[ True, False],
       [False,  True]])

In [47]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
#this array
a=np.random.randint(0,1000,100)
a


array([135, 747, 536, 949,  94, 967, 461, 369, 116, 207, 824, 137, 291,
       778, 850, 157, 306, 453, 475, 587, 503, 197, 824, 224,  66, 792,
       886, 173, 313, 425, 482, 297, 468, 351, 349, 330, 442, 792, 837,
       188, 813,  60, 956, 485, 488, 257, 230, 838, 114, 187, 507, 769,
       578, 444, 542, 116, 830, 125, 193, 150, 940, 944, 566, 848, 899,
       418, 406, 739, 797, 464, 334, 128, 994,  33, 319, 918, 797, 960,
       720,  88, 930, 279, 368, 487, 278, 211, 807, 795, 446, 582, 944,
       546, 368, 192, 405, 698, 933, 971,  66, 764], dtype=int32)

In [48]:
for num in a:
    if num>1:
        for i in range(2,num):
            if(num%i)==0:
                break
            else:
                print(num)

135
747
949
949
949
949
949
949
949
949
949
949
949
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967
967


In [49]:
a.size

100

In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
#averages

